Animated branch
EugeneOd/layout_catalog pull request #2
Opened 2020-03-06 11:41 UTC by EugeneOd

- [DEMO LINK](https://EugeneOd.github.io/layout_catalog/)

2020-03-06 17:03 UTC, denys-cheporniuk requested changes
![image](https://user-images.githubusercontent.com/37452763/76105131-0ab0ee00-5fdd-11ea-9286-272ef916070e.png)
карточка пригає і додай відстипи між бордером і картинкою)

2020-03-10 09:22 UTC, merged

2020-03-10 13:26 UTC, earthhuman41 commented on src/index.html
> +        <p class="product__current__p">69 999 грн</p>
по бэм не может быть больше 2х вложенностей, к тому же название "p" очень сомнительное

2020-03-10 13:28 UTC, earthhuman41 commented
Рамка выходит за границы экрана
<img width="499" alt="Screen Shot 2020-03-10 at 3 27 30 PM" src="https://user-images.githubusercontent.com/50083082/76316752-bdd25d80-62e3-11ea-9359-39f8f16d1519.png">

2020-03-11 09:23 UTC, vkryvytskyy commented on src/index.html
> +        <p class="product__current__p">69 999 грн</p>
fix this

2020-03-11 09:24 UTC, vkryvytskyy commented on src/styles/product-card.scss
> +      border: 3px solid #ececec;
your image should have initial border(шоб картинка не прыгала при hover)

2020-03-11 10:07 UTC, vkryvytskyy commented on src/styles/product-card.scss
> +      transition: transform 1s;
У тебя уже есть трансформ выше

2020-03-11 10:07 UTC, vkryvytskyy commented on src/styles/product-card.scss
> +      padding: 4px;
удали паддинги